FROM dduportal/arm-godev:1.4.1
MAINTAINER Damien DUPORTAL <damien.duportal@gmail.com>

ENV CONSUL_VERSION 0.5.0

RUN git clone https://github.com/hashicorp/consul ${GOPATH}/src/github.com/hashicorp/consul
WORKDIR $GOPATH/src/github.com/hashicorp/consul
RUN git checkout "v${CONSUL_VERSION}"
RUN go get -u ./...
RUN make
RUN bin/consul version

CMD ["cat","bin/consul"]